### ISSUE TITLE
Character armor & health

### ISSUE THREAD

**Issue by Chandler-M** [thunt34/1321GameDesignGroup3#23]
Great job with the fluctuation of the shop and how the game played out! One error I experienced was my character's armor changed during the battle instead of the health. I would understand if the armor how weaker the more I got hit and it wore down, however even when I did get hit, my health ended up staying the same.

**Comment by Firestrike61** [comment]
This was an intentional feature. When there is armor left the attacks only degrade that instead of the health, and once the armor equals 0, then the attacks affect health. It's just a way of having the player think about what he should buy in the shop as health can be replenished by potions while armor cannot, so there must be some strategy involved.

**Comment by Chandler-M** [comment]
I see, I just assumed it played as a percentage into the health. Nice mechanic, it's different.
